### ISSUE TITLE
Build landing page

### ISSUE THREAD

**Issue by zacck-zz** [LittleKidogo/quick_bytes#2]
## Expected Behavior
Build a landing page for the application to enable users to have an entry point into the application as they start their experience. 

### Tasks 
- [ ] Implement a layout view to hold the  navigation and content areas
- [ ] Enable Layout View to change the title of the page 
- [ ] Implement Routing to use to change the content areas and redirect users to new content areas 
- [ ] Implement the Navigation view to show relevant options so users can  be routed to them 

## Actual Behavior
Currently, The home page displays a static navigation bar and a static content area. 

## Steps to Reproduce the Problem
  1. Open the landing page 
  2. You should be able to navigate to a search result 
  3. You should be redirected to a page to add a manual upon pressing the new button
